apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: web
  ports:
    # How other pod access to the current pod.
    - port: 3000 
      # The service opens a port at this port number.
      # Listen 3000
      targetPort: 3000
